config/routes.rb
Refinery::Application.routes.draw do
  resource :newsletter, :only => [:show, :create] do
    match 'approve/:id' => :approve, :as => :approve
  end

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :mailings, :except => :show do
      post 'preview', :on => :member
      post 'preview', :on => :collection
    end
    
    scope(:path => 'mailing', :as => 'mailing') do
      root :to => 'mailings#index'
    end
    
    scope(:path => 'mailing', :as => 'mailing', :module => 'mailing') do
      resources :templates, :except => :show
      
      resources :subscribers, :except => [:new, :show, :edit]
      
      resources :newsletters, :except => :show do
        collection do
          post :update_positions
        end
      end
      
    end
  end
  
end

app/controllers/admin/mailing/newsletters_controller.rb
class Admin::Mailing::NewslettersController < Admin::BaseController

  crudify :mailing_newsletter,
          :title_attribute => 'name', :xhr_paging => true

end

app/controllers/newsletters_controller.rb
require 'guid'

class NewslettersController < ApplicationController

  before_filter :find_all_newsletters, :only => [:show, :create] 
  before_filter :find_page, :only => :show
  before_filter :find_approve_page, :only => :approve

  def show
    @subscriber = MailingSubscriber.new(:email => params[:email])
    present(@page)
  end
  
  def create
    if params[:newsletter].blank?
      flash[:error] = t('newsletters.show.no_selection')
      redirect_to newsletter_url(:email => params[:email])
      return
    end
    
    @subscriber = MailingSubscriber.where(:email => params[:email]).includes(:subscriptions).first || 
                  MailingSubscriber.new(:email => params[:email])

    updated = false
    token   = nil
    public_ids = @newsletters.map(&:id)

    if params[:unsubscribe]
      redirect_to newsletter_url and return if @subscriber.new_record?
      
      params[:newsletter].each do |id|
        id = id.to_i
        if public_ids.include?(id) && (subscription = @subscriber.subscriptions.find_by_newsletter_id(id))
          subscription.destroy
          updated = true
        end
      end
    else      
      token = Guid.new.to_s
      
      params[:newsletter].each do |id|
        id = id.to_i
        if public_ids.include?(id)
          unless @subscriber.subscriptions.find_by_id(id)
            @subscriber.subscriptions.build(:newsletter_id => id, :token => token)
            updated = true
          end
        end
      end
    end
    
    if updated
      if @subscriber.save
        if token
          host = MailingsMailer.host_from_request(request)
          MailingsMailer.confirm(@subscriber, token, host).deliver
          flash[:notice] = t('newsletters.show.confirmation_mail_send', :to => @subscriber.email)
        else
          flash[:notice] = t('newsletters.show.successfully_unsubscribed')
        end
        redirect_to newsletter_url
      else
        present(find_page)
        render :action => :show
      end
    else
      redirect_to newsletter_url(:email => params[:email])
    end
    
  end
  
  def approve
    @subscriptions = MailingNewsletterSubscriber.where(:token => params[:id].strip, :verified_at => nil).all
    
    redirect_to newsletter_url and return if @subscriptions.empty?
    
    if request.post?
      time = Time.now
      @subscriptions.each do |sub|
        sub.verified_at = time
        sub.save!
      end
    end
  end

protected

  def find_all_newsletters
    @newsletters = MailingNewsletter.frontend.order('position ASC')
  end

  def find_page
    @page = Page.where(:link_url => "/newsletter").first
  end
  
  def find_approve_page
    @page = Page.where(:link_url => "/newsletter/approve").first
  end

end

app/views/newsletters/_form.html.erb
<% selected = params[:newsletter] || [] %>
<%= form_tag newsletter_url, :method => :post, :id => 'newsletter_form' do %>
  <%= render :partial => "/shared/admin/error_messages", :locals => {
          :object => @subscriber,
          :include_object_name => true
        } %>
  <% if @newsletters.empty? %>
	  <p><%= t('.sorry_no_results') %></p>
	<% else %>
	  <% if @newsletters.size == 1 %>
		  <% newsletter = @newsletters.first %>
		  <%= hidden_field_tag "newsletter[]", newsletter.id, :id => dom_id(newsletter) %>
			<h2><%= newsletter.name %></h2>
			<%=raw newsletter.description  %>
		<% else %>
		  <table>
		  	<tbody>
		  		<% @newsletters.each do |newsletter| %>
						<tr>
		          <td>
								<%= check_box_tag "newsletter[]", newsletter.id, selected.include?(newsletter.id.to_s), :id => dom_id(newsletter) %>
							</td>
		          <td>
		            <%= label_tag dom_id(newsletter), newsletter.name %>
		            <%=raw newsletter.description  %>
		          </td>
		        </tr>
					<% end %>
				</tbody>
			</table>
		<% end %>
		<%= label_tag 'email', t('.email') %>
		<%= email_field_tag 'email', @subscriber.email %>
		<%= submit_tag t('.subscribe') %>
		<%= submit_tag t('.unsubscribe'), :name => 'unsubscribe' %>
  <% end %>
<% end %>

app/views/newsletters/approve.html.erb
<% content_for :body_content_left do %>

	<% unless request.post? %>
		<%= form_tag approve_newsletter_url(:id => params[:id]), :method => :post do %>
		  <h2><%= t('.subscribe_headline') %></h2>
			<ul>
				<% @subscriptions.each do |sub| %>
				 <li><%= sub.newsletter.name %></li>
				<% end %>
			</ul>
			<%= submit_tag t('.subscribe') %>
		<% end %>
	<% else %>
	  <h2><%= t('.successfully_subscribed_headline') %></h2>
	  <ul>
	    <% @subscriptions.each do |sub| %>
	      <li><%= sub.newsletter.name %></li>
	    <% end %>
	  </ul>
	<% end %>

<% end %>

<%= render :partial => "/shared/content_page" %>

app/views/newsletters/index.html.erb
<% content_for :body_content_left do %>
  <ul id="newsletters">
    <% @newsletters.each do |newsletter| %>
      <li>
        <%= newsletter.name %>
      </li>
    <% end %>
  </ul>
<% end %>

<%= render :partial => "/shared/content_page" %>

app/views/newsletters/show.html.erb
<% flash.each do |key, value| %>
 <div id='flash' class="flash flash_<%= key %>">
   <%= value %>
 </div>
<% end %>

<% content_for :body_content_left do %>
  <%= render :partial => 'form' %>
<% end %>

<%= render :partial => "/shared/content_page" %>