config/routes.rb
Refinery::Application.routes.draw do
  resource :newsletter, :only => [:show, :create] do
    match 'approve/:id' => :approve, :as => :approve
  end

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :mailings, :except => :show do
      post 'preview', :on => :member
      post 'preview', :on => :collection
    end
    
    scope(:path => 'mailing', :as => 'mailing') do
      root :to => 'mailings#index'
    end
    
    scope(:path => 'mailing', :as => 'mailing', :module => 'mailing') do
      resources :templates, :except => :show
      
      resources :subscribers, :except => [:new, :show, :edit]
      
      resources :newsletters, :except => :show do
        collection do
          post :update_positions
        end
      end
      
    end
  end
  
end

app/models/mailing.rb
require 'nokogiri'

class Mailing < ActiveRecord::Base  
  acts_as_indexed :fields => [:subject, :body, :html_body]

  validates :from, :subject, :presence => true
  
  belongs_to :created_by, :class_name => 'User'
  belongs_to :updated_by, :class_name => 'User'
  
  has_and_belongs_to_many :newsletters, :class_name => 'MailingNewsletter', :uniq => true
  has_and_belongs_to_many :newsletter_recipients, :class_name => 'MailingSubscriber',:join_table => :mailing_subscribers_mailings, :uniq => true
  
  belongs_to :job, :class_name => 'Delayed::Backend::ActiveRecord::Job'
  
  before_save :make_urls_absoulute
  
  def subscribers
    MailingSubscriber.
      joins(:subscriptions => {:newsletter => :mailings}).
      where('mailing_newsletter_subscribers.verified_at is not null').
      where(:mailings => {:id => self.id})
  end
  
  def newsletters_attributes=(attrs)
    ids = Hash[ attrs.select {|k,v| v[:checked] != '0' } ].keys.map(&:to_i) # ruby 1.8 Hash#select returns Array instead of Hash
    selected = ids.empty? ? ids : MailingNewsletter.find(ids)
    
    self.newsletters -= self.newsletters.reject {|n| selected.include?(n) }
    
    (selected - self.newsletters).each {|letter| self.newsletters << letter }
  end
  
  def sent?
    !self.sent_at.nil?
  end
  
  def finished?
    !self.finished_at.nil?
  end
  
  def to_liquid
    { 
      'subject'    => self.subject,
      'body'       => self.body,
      'html_body'  => self.html_body,
      'created_at' => self.created_at,
      'updated_at' => self.updated_at
    }
  end
  
  def make_urls_absoulute
    if !self.html_body.blank? && self.html_body_changed?
      doc = Nokogiri::HTML(self.html_body)
      doc.xpath("//a").each {|n| n['href'] = fix_url(n['href']) }
      doc.xpath("//img").each {|n| n['src'] = fix_url(n['src']) }
      self.html_body = doc.root.children.first.children.to_s # /html/body/...
    end
  end
  
  protected
  def fix_url(url)
    return url if url.blank?
    @asset_url ||= Refinery::Mailings.asset_url
    url !~ /^https?:\/\// ? File.join(@asset_url, url) : url
  end
  
end

app/controllers/admin/mailing/mailing_templates_controller.rb
class Admin::Mailing::MailingTemplatesController < Admin::BaseController

  crudify :mailing_template,
          :title_attribute => 'slug', :xhr_paging => true
            
end

app/controllers/admin/mailing/newsletters_controller.rb
class Admin::Mailing::NewslettersController < Admin::BaseController

  crudify :mailing_newsletter,
          :title_attribute => 'name', :xhr_paging => true

end

app/controllers/admin/mailing/subscribers_controller.rb
class Admin::Mailing::SubscribersController < Admin::BaseController
  before_filter :find_all_newsletters, :only => [:index, :update]
  
  respond_to :js, :only => :update

  CONDITION = "mailing_newsletter_subscribers.verified_at is not null"

  crudify :mailing_subscriber,
          :include => [:newsletters],
          :conditions => CONDITION,
          :search_conditions => CONDITION,
          :title_attribute => 'email', 
          :order => 'email ASC',
          :xhr_paging => true

  def update
    current    = @mailing_subscriber.newsletters
    requested  = MailingNewsletter.find(params[:newsletter])
    to_destroy = current   - requested
    to_create  = requested - current
    verified   = Time.now
    
    to_create.each do |newsletter|
      @mailing_subscriber.subscriptions.build(:newsletter => newsletter, :verified_at => verified)
    end
    
    to_destroy.each do |newsletter|
      sub = @mailing_subscriber.subscriptions.find_by_newsletter_id(newsletter.id)
      sub.destroy if sub
    end
    
    @mailing_subscriber.save!
    @mailing_subscriber.reload
  end

  protected
  
  def find_mailing_subscriber
    @mailing_subscriber = MailingSubscriber.find(params[:id])
  end
  
  def find_all_newsletters
    @newsletters = MailingNewsletter.all
  end

end

app/controllers/admin/mailing/templates_controller.rb
class Admin::Mailing::TemplatesController < Admin::BaseController

  crudify :mailing_template,
          :title_attribute => 'slug', :xhr_paging => true
            
end

app/controllers/admin/mailings_controller.rb
class Admin::MailingsController < Admin::BaseController

  crudify :mailing,
          :title_attribute => 'subject', 
          :sortable => false,
          :order => 'created_at DESC'
          
  before_filter :find_all_newsletters, :only => [:new, :edit, :create, :update]
  before_filter :change_only_unsent_mailings, :only => :update
  
  def create
    save ? continue_or_redirect : render(:action => 'new')
  end

  def update
    save ? continue_or_redirect : render(:action => 'edit')
  end
  
  def preview
    @mailing = params[:id] ? find_mailing : Mailing.new
    
    html = params[:format] == 'html'
    
    @mailing.attributes = params[:mailing]
    @mailing.make_urls_absoulute if html
    
    host = MailingsMailer.host_from_request(request)
    mail = MailingsMailer.send_mail(@mailing, { :to => 'preview@example.org' }, host)
    
    content = if html
      if mail.multipart?
        part = mail.parts.find{|part| part.content_type =~ /^text\/html/ }
        part ? part.body : nil
      elsif mail.content_type =~ /^text\/html/
        mail.body.decoded
      end
    else
      body = if mail.multipart?
        part = mail.parts.find{|part| part.content_type =~ /^text\/plain/ }
        part ? part.body : nil
      elsif mail.content_type =~ /^text\/plain/
        mail.body.decoded
      end
      !body.blank? ? "<html><body><pre>#{body}</pre></body></html>" : nil
    end
    content = content.blank? ? "<html><body><h1>#{t('admin.mailing.preview.no_text')}</h1></body></html>" : content
    render :text => content, :layout => false
  end

  protected
  def save
    @mailing ||= Mailing.new
    @mailing.attributes = params[:mailing]
    
    new_record = @mailing.new_record?
    
    @mailing.created_by = current_user if new_record
    @mailing.updated_by = current_user
    
    host = MailingsMailer.host_from_request(request)
    
    if @mailing.save
      if params[:test]
        MailingsMailer.send_mail(@mailing, {:to => params[:test_email]}, host).deliver
        flash.notice = t('admin.mailings.mailing.test_mail_sent', :what => "'#{@mailing.subject}'")
      elsif params[:send]
        job = Delayed::Job.enqueue Refinery::Mailings::NewsletterJob.new(@mailing.id, host)
        @mailing.update_attributes :job_id => job.id, :sent_at => Time.now
        flash.notice = t('admin.mailings.mailing.mail_sent', :what => "'#{@mailing.subject}'")
      else
        msg = new_record ? 'refinery.crudify.created' : 'refinery.crudify.updated'
        flash.notice = t(msg, :what => "'#{@mailing.subject}'")
      end
      return true
    end
    
    false
  end
  
  def continue_or_redirect
    params[:continue] || params[:test] ? render(:action => 'edit') : redirect_to(admin_mailings_url)
  end
  
  def find_all_newsletters
    @newsletters = MailingNewsletter.all
  end
  
  def change_only_unsent_mailings
    if @mailing.sent?
      redirect_to admin_mailings_url
    end
  end

end

app/controllers/newsletters_controller.rb
require 'guid'

class NewslettersController < ApplicationController

  before_filter :find_all_newsletters, :only => [:show, :create] 
  before_filter :find_page, :only => :show
  before_filter :find_approve_page, :only => :approve

  def show
    @subscriber = MailingSubscriber.new(:email => params[:email])
    present(@page)
  end
  
  def create
    if params[:newsletter].blank?
      flash[:error] = t('newsletters.show.no_selection')
      redirect_to newsletter_url(:email => params[:email])
      return
    end
    
    @subscriber = MailingSubscriber.where(:email => params[:email]).includes(:subscriptions).first || 
                  MailingSubscriber.new(:email => params[:email])

    updated = false
    token   = nil
    public_ids = @newsletters.map(&:id)

    if params[:unsubscribe]
      redirect_to newsletter_url and return if @subscriber.new_record?
      
      params[:newsletter].each do |id|
        id = id.to_i
        if public_ids.include?(id) && (subscription = @subscriber.subscriptions.find_by_newsletter_id(id))
          subscription.destroy
          updated = true
        end
      end
    else      
      token = Guid.new.to_s
      
      params[:newsletter].each do |id|
        id = id.to_i
        if public_ids.include?(id)
          unless @subscriber.subscriptions.find_by_id(id)
            @subscriber.subscriptions.build(:newsletter_id => id, :token => token)
            updated = true
          end
        end
      end
    end
    
    if updated
      if @subscriber.save
        if token
          host = MailingsMailer.host_from_request(request)
          MailingsMailer.confirm(@subscriber, token, host).deliver
          flash[:notice] = t('newsletters.show.confirmation_mail_send', :to => @subscriber.email)
        else
          flash[:notice] = t('newsletters.show.successfully_unsubscribed')
        end
        redirect_to newsletter_url
      else
        present(find_page)
        render :action => :show
      end
    else
      redirect_to newsletter_url(:email => params[:email])
    end
    
  end
  
  def approve
    @subscriptions = MailingNewsletterSubscriber.where(:token => params[:id].strip, :verified_at => nil).all
    
    redirect_to newsletter_url and return if @subscriptions.empty?
    
    if request.post?
      time = Time.now
      @subscriptions.each do |sub|
        sub.verified_at = time
        sub.save!
      end
    end
  end

protected

  def find_all_newsletters
    @newsletters = MailingNewsletter.frontend.order('position ASC')
  end

  def find_page
    @page = Page.where(:link_url => "/newsletter").first
  end
  
  def find_approve_page
    @page = Page.where(:link_url => "/newsletter/approve").first
  end

end

app/helpers/admin/mailings_helper.rb
module Admin::MailingsHelper
  
  def mailing_templates
    MailingTemplate.order('slug ASC').all(:select => :slug).map {|t| t.slug.gsub(/\.\w+$/, '') }.uniq
  end
  
end

app/views/admin/mailing/newsletters/_actions.html.erb
<ul>
  <% if Admin::Mailing::NewslettersController.searchable? %>
    <li>
      <%= render :partial => "/shared/admin/search",
                  :locals => {
                    :url => admin_mailing_newsletters_url
                  } %>
    </li>
  <% end %>
<% if !searching? and Admin::Mailing::NewslettersController.sortable? and MailingNewsletter.count > 1 %>
  <li>
    <%= link_to t('.reorder', :what => "Newsletters"),
                 admin_mailing_newsletters_url,
                 :id => "reorder_action",
                 :class => "reorder_icon" %>

    <%= link_to t('.reorder_done', :what => "Newsletters"),
                 admin_mailing_newsletters_url,
                 :id => "reorder_action_done",
                 :style => "display: none;",
                 :class => "reorder_icon" %>
  </li>
<% end %>
</ul>

<%= render '/admin/mailing/sidebar' %>

app/views/admin/mailing/newsletters/_form.html.erb
<%= form_for [:admin, @mailing_newsletter] do |f| -%>
  <%= render :partial => "/shared/admin/error_messages", :locals => {
          :object => @mailing_newsletter,
          :include_object_name => true
        } %>
  
  <div class='field'>
    <%= f.label :name -%>
    <%= f.text_field :name, :class => 'larger widest' -%>
  </div>
  
  <div class='field'>
    <div id='page-tabs' class='clearfix ui-tabs ui-widget ui-widget-content ui-corner-all'>
      <ul id='page_parts'>
        <li class='ui-state-default ui-state-active'>
          <%= link_to MailingNewsletter.human_attribute_name(:description), "#description" %>
        </li>
      </ul>

      <div id='page_part_editors'>
        <div class='page_part' id='description'>
          <%= f.text_area :description, :rows => 20, :class => 'wymeditor widest' -%>
        </div>
      </div>
    </div>
  
  <div class='field'>
    <%= f.label :public -%>
    <%= f.check_box :public -%>
  </div>
  
  <%= render :partial => "/shared/admin/form_actions",
              :locals => {
                :f => f,
                :continue_editing => false,
                :delete_title => t('delete', :scope => 'admin.newsletters.newsletter'),
                :delete_confirmation => t('message', :scope => 'shared.admin.delete', :title => @mailing_newsletter.name)
              } %>
<% end -%>
<% content_for :javascripts do %>
  <script>
    $(document).ready(function(){
      page_options.init(false, '', '');
    });
  </script>
<% end %>

app/views/admin/mailing/newsletters/_newsletter.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(newsletter) -%>">
  <span class='title'>
    <%= newsletter.name %>
    <span class="preview">&nbsp;</span>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag("application_go.png"), newsletter_url,
        :title => t('.view_live_html'),
        :target => "_blank" %>
    <%= link_to refinery_icon_tag("application_edit.png"), edit_admin_mailing_newsletter_path(newsletter),
         :title => t('.edit') %>
    <%= link_to refinery_icon_tag("delete.png"), admin_mailing_newsletter_path(newsletter),
        :class => "cancel confirm-delete",
        :title => t('.delete'),
        :confirm => t('message', :scope => 'shared.admin.delete', :title => newsletter.name),
        :method => :delete %>
  </span>
</li>

app/views/admin/mailing/newsletters/_newsletters.html.erb
<%= will_paginate @mailing_newsletters %>
<%= render :partial => "sortable_list" %>

app/views/admin/mailing/newsletters/_records.html.erb
<% if searching? %>
  <h2><%= t('results_for', :scope => 'shared.admin.search', :query => params[:search]) %></h2>
<% end %>
<% if @mailing_newsletters.any? %>
  <div class='pagination_container'>
    <%= render :partial => 'newsletters' %>
  </div>
<% else %>
  <p>
    <% unless searching? %>
      <strong>
        <%= t('.no_items_yet') %>
      </strong>
    <% else %>
      <%= t('no_results', :scope => 'shared.admin.search') %>
    <% end %>
  </p>
<% end %>

app/views/admin/mailing/newsletters/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'newsletter', :collection => @mailing_newsletters %>
</ul>
<%= render :partial => "/shared/admin/sortable_list",
            :locals => {
              :continue_reordering => (local_assigns.keys.include?(:continue_reordering)) ? continue_reordering : true
            } %>

app/views/admin/mailing/newsletters/index.html.erb
<% 
  content_for :stylesheets, stylesheet_link_tag('refinery/refinerycms-mailings')
  content_for :javascripts, javascript_include_tag('refinery/refinerycms-mailings') 
%>

<section id='records'>
  <%= render :partial => 'records' %>
</section>
<aside id='actions'>
  <%= render :partial => 'actions' %>
</aside>
<%= render :partial => '/shared/admin/make_sortable',
            :locals => {
              :tree => false
            } if !searching? and Admin::Mailing::NewslettersController.sortable? and MailingNewsletter.count > 1 %>